apiVersion: v1
kind: Service
metadata:
  labels:
    app: collector
  name: collector
  namespace: pivothr
spec:
  ports:
    - name: "8110"
      port: 8110
      targetPort: 8110
  selector:
    app: collector
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: collector
  name: collector
  namespace: pivothr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  strategy:
    type: RollingUpdate
  template:
    metadata:

      labels:
        app: collector
    spec:
      priorityClassName: high-priority
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/pivotstudio/collector:latest
        name: collector
        ports:
          - containerPort: 8110
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests: 
            cpu: 50m
            memory: 50Mi
      restartPolicy: Always
status: {}
